config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  devise_for :users

  root to: 'static#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/submission.rb
class Submission < ApplicationRecord
  mount_uploader :submission_image, SubmissionImageUploader
  mount_uploader :submission_image, SubmissionVideoUploader

  belongs_to :user

  validates :title, presence: true
  validates :body, length: { maximum: 8000}
  validates :url, url: true, allow_blank: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :submissions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @submissions = Submission.all
  end

  def show
  end

  def new
    @submission = current_user.submissions.build
  end

  def edit
  end

  def create
    @submission = current_user.submissions.build(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: "Submission was successfully created." }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_submission
    @submission = Submission.find(params[:id])
  end

  def submission_params
    params.require(:submission).permit(:title, :body, :url, :submission_image, :submission_video)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_svg(name, styles: "fill-current text-gray-400", title: nil)
    filename = "#{name}.svg"
    title ||= name.underscore.humanize
    inline_svg_tag(filename, aria: true, nocomment: true, title: title, class: styles)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webbit</title>
    <%= render "shared/head" %>
  </head>

  <body class="m-4">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <nav class="js-nav bg-white py-2 border-b border-gray-400" role="navigation" aria-label="
    main navigation">
      <div class="flex flex-wrap items-center justify-center lg:justify-start lg:content-center [px-4 lg:px-6">
        <%= link_to root_path, class: "leading-normal no-underline text-gray-800 my-2 md:my-0" do %>
          <h1 class="text-lg pr-2 font-bold">WEBBIT</h1>
        <% end %>

        <div class="flex flex-wrap justify-start w-full lg:w-2/3">
          <div class="w-full lg:w-1/4 px-0 md:px-2 mb-2 lg:mb-0">
              <ul>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Submissions", submissions_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Log in", new_user_session_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/shared/_head.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/submissions/_form.html.erb
<%= form_with(model: submission) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :submission_image %>
    <%= form.file_field :submission_image %>
  </div>

  <div class="field">
    <%= form.label :submission_video %>
    <%= form.file_field :submission_video %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.title %></td>
        <td><%= submission.body %></td>
        <td><%= submission.url %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @submission.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @submission.body %>
</p>

<p>
  <strong>Url:</strong>
  <%= @submission.url %>
</p>

<%#= debug(@submission.submission_image) %>
<p>
  <strong>Submission Image:</strong>
  <%= image_tag @submission.submission_image.large.url, width: 400 %>
</p>

<p>
  <strong>Submission Video:</strong>
  <%#= image_tag @submission.submission_image, width: 400 %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>